### ISSUE TITLE
Destroy spelling mistake

### ISSUE THREAD

**Issue by NoSharp** [Facepunch/sbox-hidden#3]
In here:
https://github.com/Facepunch/sbox-hidden/blob/95b63c7594ba1ac9727c2b968c7c35024cae717e/code/entities/LaserDot.cs#L30
and
https://github.com/Facepunch/sbox-hidden/blob/c6726e436aef30887501eb00cfd70c7bb91e0046/code/player/Player.cs#L157
Sorry to be a grammar nazi :/

**Comment by Trojaner** [comment]
Duplicate of https://github.com/Facepunch/sbox-issues/issues/10

**Comment by NoSharp** [comment]
I'll close, apologies for the duplicate
